version: '3'

services:
#################
#  API CONTAINER
#################
    api:
        build:
            context: ./api
        image: samchipp/capstone:api
        expose: 
            - 80
        ports: 
            - 80:80
        volumes:
            - ./api/src:/src/app/api/src
        command: npm run start

####################
#  CLIENT CONTAINER
####################
    client:
        build:
            context: ./client
        image: samchipp/capstone:client
        expose:
            - 3000
        ports: 
            - 3000:3000
        stdin_open: true
        volumes:
            - ./client/src:/src/app/client/src
            - ./client/public:/app/client/public